travis:
  secure:
    BINSTAR_TOKEN: J/Km2vN2zCu/TJqrQOVzA5dYtOvaiMsm4a58c5oFYQ+PjY0xJBOMtlFWA9E4I+Iz6L3wNPkzzyD9ByQgqTptLfq/csPQ6UdYGgyNnMwONhY8dW/S0imN3C7gTtdjCXhaV7HMaKtYe9fOpthg1WPo7ZEsDNP6ILyoXje78Nn6pvTojtEG/DK9Y20j7cnFeOchgV7xxYZseBg0Vvc4vR6R+pAre58AIVO01etzk6NtxSExR1VD2LP0Y7Wz5AGiHFtle/T/5Tybk85GUUwfWQrDc6bsICTfFQzuxtrfHRmqXEA/ALVffDX704THfVnZQtK9oyti+i5o2kXwVA0QqupsJaviN7h5QCnlFJDvkk3DXF5ElNtixUd8AQ/prUnYNLeMdJCF+Nvws7WGh6nKUNpiIeFsSmji/62/WFnpH83+nrUMtLHYNGbOuYOjsVUCuVNoRrfF1wfIH3SxKCP7TY5x5GbjVFfoyF0GlkCv2Ll0JjbMv9w3dxVI5+UbiRu1A5Aj45z5wiflYN9frczNThONTH6wwQ6LqrMUDyqrKDerwPxjE7pBnSB+1tPXERedhopg0t2pTvtQ1ZJlRzz/5BWduWAzDFXamcs2j+QqODFEhN4B4ppm0DELnD4gs4EoTjD1PoNYoDvzoAr981Xr01IStcc0N34ozBQw32Wt0eFKCoE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
